apiVersion: v1
kind: Service
metadata:
  name: education-web
  namespace: education-system
  labels:
    app.kubernetes.io/name: education-system
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: education-system
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
