apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: education-system
  labels:
    app.kubernetes.io/name: education-system
    app.kubernetes.io/component: sqlserver
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: education-system
    app.kubernetes.io/component: sqlserver
  ports:
    - name: sql
      port: 1433
      targetPort: sql
